[project]
name = 'project-template'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[contracts.counter]
path = 'contracts/counter.clar'
clarity_version = 4
epoch = "latest" # 3.3
